### ISSUE TITLE
Contracts from the public space that don't belong to a registered contracting authority cannot be viewed

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#28]
If the service `PCFilingApp?action=getContractJson&copyContractURL={contract URI}` is called with a contract URI that is present in the public data space but isn't associated with a contracting authority registered in the PC Filing App, the service throws an HTTP 500 error with the message such as the following:

```
javax.servlet.ServletException: cz.opendata.tenderstats.pcfapp.PCFappException: Contract http://linked.opendata.cz/resource/vestnikverejnychzakazek.cz/public-contract/343261-7303010043261 not found.
    at cz.opendata.tenderstats.PCFilingApp.doGetPost(PCFilingApp.java:755)
    at cz.opendata.tenderstats.AbstractComponent.doGet(AbstractComponent.java:154)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:751)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:566)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
    at org.eclipse.jetty.server.Server.handle(Server.java:461)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
    at java.lang.Thread.run(Thread.java:724)
Caused by: cz.opendata.tenderstats.pcfapp.PCFappException: Contract http://linked.opendata.cz/resource/vestnikverejnychzakazek.cz/public-contract/343261-7303010043261 not found.
    at cz.opendata.tenderstats.pcfapp.PCFappModelContract.getContractAsJson(PCFappModelContract.java:221)
    at cz.opendata.tenderstats.PCFilingApp.doGetPost(PCFilingApp.java:752)
    ... 23 more
```

Look up of contracts not associated with a registered contracting authority needs to work in order to view contracts suggested by the matchmaker.

**Comment by propi** [comment]
Now, you can use this: PCFilingApp?action=getContractJson&public=true&copyContractURL=http://linked.opendata.cz/resource/vestnikverejnychzakazek.cz/public-contract/364155-7302010064155

with the "public=true" query param the session is not necessary and the contract is searching within the public graph..

Furthermore, it is possible to read any query param in JSP by this: ${param.contractURI} for the contractURI query param..(e.g.: buyer-view-event.jsp?contractURI=http://linked.opendata.cz/resource/vestnikverejnychzakazek.cz/public-contract/364155-7302010064155)
