### ISSUE TITLE
src/test/scala/cz/opendata/tenderstats/ServletTest.scala fails

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#29]
When running `mvn install` the `ServletTest` fails:

```
Running cz.opendata.tenderstats.ServletTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.297 sec <<< FAILURE! - in cz.opendata.tenderstats.ServletTest
testMatchmaker(cz.opendata.tenderstats.ServletTest)  Time elapsed: 0.296 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1499)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1322)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:721)
    at javax.servlet.GenericServlet.<clinit>(GenericServlet.java:95)
    at cz.opendata.tenderstats.ServletTest.testMatchmaker(ServletTest.scala:21)
```

**Comment by propi** [comment]
ServletTest was disabled
